//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMunicipios
    {
        public string mun_id { get; set; }
        public string mun_Nombre { get; set; }
        public string dep_Id { get; set; }
        public int mun_UsuCreacion { get; set; }
        public System.DateTime mun_FechaCreacion { get; set; }
        public Nullable<int> mun_UsuModificacion { get; set; }
        public Nullable<System.DateTime> mun_FechaModificacion { get; set; }
        public bool mun_Estado { get; set; }
    
        public virtual tbDepartamentos tbDepartamentos { get; set; }
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
